<?php

/**
 * @file
 * Views vertical_tabs style plugin code.
 */

/**
 * Implements hook_views_api().
 */
function image_collage_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_preprocess_HOOK() for theme_views_view_vertical_tabs().
 */
function template_preprocess_views_image_collage(&$vars) {
  $view = $vars['view'];
  $rows = $vars['rows'];
  $style = $view->style_plugin;
  $options = $style->options;
  $group = $view->name . '_' . $view->current_display;

  $element = array(
    '#type' => 'vertical_tabs',
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'image_collage') . '/image_collage.js'),
    ),
  );
  $myvars = array();
  $default_row_class = isset($options['default_row_class']) ? $options['default_row_class'] : FALSE;
  $row_class_special = isset($options['row_class_special']) ? $options['row_class_special'] : FALSE;
  // Set up striping values.
  $count = 0;
  $max = count($rows);
  $summaries = array();
  foreach ($rows as $id => $row) {
    $myvars[$id] = array();
    $html_id = drupal_html_id($group . '-' . $id);
    $classes = array();
    $count++;
    if ($default_row_class) {
      $classes[] = 'views-row';
      $classes[] = 'views-row-' . $count;
    }
    if ($row_class_special) {
      $classes[] = 'views-row-' . ($count % 2 ? 'odd' : 'even');
      if ($count == 1) {
        $classes[] = 'views-row-first';
      }
      if ($count == $max) {
        $classes[] = 'views-row-last';
      }
    }

    if ($row_class = $view->style_plugin->get_row_class($id)) {
      $classes[] = $row_class;
    }

    $field = $options['name'];
    $name = '';
    if (isset($view->field[$field])) {
      $name = $style->get_field($id, $field);
      if ($view->field[$field]->options['label']) {
        $name = $name;
      }
      $name = strip_tags(htmlspecialchars_decode($name));
      $myvars[$id]['name'] = $name;
    }
    $field = $options['quote'];
    $quote = '';
    if (isset($view->field[$field])) {
      $quote = $style->get_field($id, $field);
      if ($view->field[$field]->options['label']) {
        $quote = $quote;
      }
      $quote = strip_tags(htmlspecialchars_decode($quote));
      $myvars[$id]['quote'] = $quote;
    }
    $field = $options['tagline'];
    $tagline = '';
    if (isset($view->field[$field])) {
      $tagline = $style->get_field($id, $field);
      if ($view->field[$field]->options['label']) {
        $tagline = $tagline;
      }
      $tagline = strip_tags(htmlspecialchars_decode($tagline));
      $myvars[$id]['tagline'] = $tagline;
    }
    $field = $options['bio'];
    $bio = '';
    if (isset($view->field[$field])) {
      $bio = $style->get_field($id, $field);
      if ($view->field[$field]->options['label']) {
        $bio = $bio;
      }
      $myvars[$id]['bio'] = $bio;
      
    }
    $field = $options['image'];
    $img = '';
    if (isset($view->field[$field])) {
      $img = $style->get_field($id, $field);
      if ($view->field[$field]->options['label']) {
        $img = $img;
      }
      $myvars[$id]['img'] = $img;
    }
    
    if (!empty($bio)) {
      $summaries[$html_id] = $bio;
    }

    $element[$id] = array(
      '#title' => $name,
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#children' => $row,
      '#description' => $quote,
      '#attributes' => array(
        'class' => $classes,
        'id' => $html_id,
      ),
    );
  }
  $mod_path = drupal_get_path('module', 'image_collage');
  drupal_add_js($mod_path . '/flexslider/jquery.flexslider.js', array('group' => JS_DEFAULT));
  drupal_add_js($mod_path .'/image_collage.js', array('group' => JS_DEFAULT));
  drupal_add_css($mod_path . '/flexslider/flexslider.css', array('group' => CSS_DEFAULT));
  drupal_add_css($mod_path . '/css/image_collage.css', array('group' => CSS_DEFAULT));
  //$vars['image_collage'][] = $element;
  
  $vars['blocks'] = $myvars;
}
